ALTER TABLE users
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN updated_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

ALTER TABLE categories
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN updated_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

ALTER TABLE products
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN updated_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

ALTER TABLE carts
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN updated_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

ALTER TABLE cart_items
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN updated_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

ALTER TABLE orders
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN updated_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

ALTER TABLE order_items
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN updated_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';